### ISSUE TITLE
Line numbers in error/warning messages when referring to deny.toml are wrong

### ISSUE THREAD

**Issue by sdroege** [EmbarkStudios/cargo-deny#264]
This for example is a `[[bans.skip]]` [around line 30](https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/blob/6de1ca7ed3476cd29b3bfc2ca0b83b858c537603/deny.toml#L33-39) and nothing around line 1.

```
warning: skipped crate was not encountered
  ┌─ /home/slomo/Projects/rust/gst-plugin-rs/deny.toml:1:1
  │
1 │ [advisories]
  │ ^ no crate matched these criteria
```

**Comment by Jake-Shadle** [comment]
This is a limitation with how we get span information when parsing the toml configuration files, which is essentially just a copy of what the [`toml`](https://github.com/alexcrichton/toml-rs/blob/master/src/spanned.rs) crate itself does, we just tend to always use [inline](https://github.com/EmbarkStudios/cargo-deny/blob/28fa7643887b5765f179f376fa2e5dae8084d25a/deny.toml#L23-L29) arrays/objects, which does work correctly.

I think fixing this would be very valuable, since I'm now remembering this is the same issue for why we cheat and generate some toml when displaying the spans for where a value came from in a Cargo.toml manifest, but I might not be able to get to it for a while.

**Comment by Jake-Shadle** [comment]
Related: #136
