### ISSUE TITLE
Allow all git repos from host (for self-hosted corporate git)

### ISSUE THREAD

**Issue by adamchalmers** [EmbarkStudios/cargo-deny#351]
**Is your feature request related to a problem? Please describe.**
I write Rust for work, and I'd like to allow any Git dependency from my work's self-hosted git server. Right now, the only way I see to do that is to manually add every Git repo I depend on to the `allow-git` list. If these repos were on Github, I could just trust my work's org, however, we use a private work git server. 

**Describe the solution you'd like**
I can think of two solutions:

1. A new `allow-git-hosts` key, of type List<String>, which would trust any Git repo whose path has one of the given hosts.
2. Allow wildcards `*` in the entries under `allow-git`, so that I can add a wildcard in the host or path, so that all repos from my org's git server are trusted.

**Describe alternatives you've considered**
It's really not too hard to manually add every private repo I want to use.

**Comment by Jake-Shadle** [comment]
I think having a `private` or `internal` entry under `allow-orgs` would probably be the most clear since it would only accept a host + optional path that the private repos would be all rooted to.

I haven't used a purely internal git server in years so I completely forgot about this use case, thanks for posting the issue!

**Comment by adamchalmers** [comment]
Yeah, that sounds great, that would meet my needs nicely!
