### ISSUE TITLE
cargo-deny action failure --possibly due to use of a beta on crates.io?

### ISSUE THREAD

**Issue by daringordon** [EmbarkStudios/cargo-deny#367]
**Describe the bug**

I've created a very basic project illustrating the problem I'm experiencing during a CI run:  https://github.com/daringordon/cargo_deny_error_reproduction/runs/3701686133?check_suite_focus=true#step:4:9

Is the problem related to use of a beta version crate?  Thanks for checking.

**Device:**
 - OS: Debian Stretch
 - Version:  latest cargo deny action v1

**Comment by Jake-Shadle** [comment]
I believe this is because you have set [`CARGO_NET_GIT_FETCH_WITH_CLI`](https://github.com/daringordon/cargo_deny_error_reproduction/blob/0a3312d20fa5716dd33abbc79ca9964e3e26c049/.github/workflows/platform.yml#L19). The cargo-deny-action doesn't include the git executable so that fails, is there a reason you are using `CARGO_NET_GIT_FETCH_WITH_CLI`? If there is you would need to install git before running cargo-deny.

**Comment by daringordon** [comment]
@Jake-Shadle `CARGO_NET_GIT_FETCH_WITH_CLI` was necessary to address an error that triggered before this one: cargo-deny's runtime was failing to access private github repositories, despite that ssh-agent is set up for the workflow and used successfully in other tasks.  Removing `CARGO_NET_GIT_FETCH_WITH_CLI` did clear this issue, leaving me to deal with the prior one again.

**Comment by Jake-Shadle** [comment]
Ahh I see, I would open a bug on cargo-deny-action then to include git in the container.
