### ISSUE TITLE
[Feature Request] Add field `warn` to key `licenses`

### ISSUE THREAD

**Issue by jblachly** [EmbarkStudios/cargo-deny#387]
As a new user of `cargo-deny`, I was really pleased with the initial sample `deny.toml` -- especially the block to fix `ring` !

However, the top of the file reads:
```
# Note that all fields that take a lint level have these possible values:
# * deny - An error will be produced and the check will fail
# * warn - A warning will be produced, but the check will not fail
# * allow - No warning or error will be produced, though in some cases a note
# will be
```

and I thus attempted to add a `warn` field to the `licenses` section in order to allow, but warn about licenses that require me to take a specific action (namely, OpenSSL, and some others require a note stating "This software includes portions derived from whatever...").

Unfortunately, in violation of the principle of least surprise, this is not possible:

```
2021-12-30 00:16:00 [ERROR] failed to deserialize config from '/Users/james/src/protograph/pgapi_rocket/deny.toml': unknown field `warn`, expected one of `private`, `unlicensed`, `allow-osi-fsf-free`, `copyleft`, `default`, `confidence-threshold`, `deny`, `allow`, `unused-allowed-license`, `clarify`, `exceptions` for key `licenses` at line 216 column 1
```

Thanks for considering. If this field is acceptable to the maintainers I can try to work on a PR (eventually).

**Comment by Jake-Shadle** [comment]
It sounds like you have confused the possible lint level values with a field name? I would accept a PR that cleans up any confusing language in the documentation or template.

**Comment by jblachly** [comment]
> It sounds like you have confused the possible lint level values with a field name?

Yes, obviously. I mentioned [The Principle of Least Surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) because I expected that if at least 2/3 of the lint levels were also optional `[license]` keys, perhaps `warn` was as well. 

Do you not think the proposed behavior (viz., a "warn" field in the licenses section with same semantics as "warn" lint level) given the example use case (OpenSSL license) is reasonable and useful?

**Comment by Jake-Shadle** [comment]
I don't think it would make sense to add a `warn` field to the licenses check, at least, not until specific diagnostic codes can be upgraded to errors, as otherwise you will just have warnings spammed at all times, which won't block CD since they won't fail the check.

If using a specific license requires some action, it seems the easiest thing to do would be to not accept the license by default, which will cause a failure if a dependency is added that does use that license, and then once the (one time?) action is performed you can add an [exception](https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html#the-exceptions-field-optional) for that dependency.

**Comment by jblachly** [comment]
> at least, not until specific diagnostic codes can be upgraded to errors, as otherwise you will just have warnings spammed at all times, which won't block CD since they won't fail the check.

Thanks for clarifying your thinking and proposing a possible future solution. I'll close this for now.
