### ISSUE TITLE
Add "init" subcommand

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/cargo-deny#42]
Adding an `init` subcommand that generates a deny.toml with the default values would be a nice little feature.

**Comment by foresterre** [comment]
I made a draft PR in #48. 

I intend to add the following:
* options for `allow` and `deny` licenses fields.
* a test suite

The test suite requires a bit of thought, but for now I have been using the Command API similar to what I have done in [sic](https://github.com/foresterre/sic/blob/master/tests/cli_image_operation_args.rs). [cargo](https://github.com/rust-lang/cargo/blob/master/crates/cargo-test-support/src/lib.rs#L1759) seems to use a very similar testing process. This part of the code is not included in the PR yet because it needs a bit more generalization and cleaning up.

If you want things removed, changed, added please let me know :smiley:

**Comment by Jake-Shadle** [comment]
Oops, closed by #48
