### ISSUE TITLE
Add list subcommand

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/cargo-deny#5]
Add a `list` subcommand, similar to cargo license.

**Comment by repi** [comment]
This you have already implemented, and looks nice! :) 

We talk today about changing the json output though to be a flat list of the dependencies and the list of licenses they use. Instead of a list of crates for each license.

And also talked about clarifying the output slightly more in the human readable default output for crates that use multiple licenses as they show up multiple times which is good but can be confusing

**Comment by Jake-Shadle** [comment]
This is pretty much done a of 89688eb30c938cd51cf299c53ca67059e153eee9
