### ISSUE TITLE
invalid licensee "LGPL-2.1-or-later"

### ISSUE THREAD

**Issue by jyn514** [EmbarkStudios/cargo-deny#514]
**Describe the bug**

I added `[licenses] allow = ["LGPL-2.1-or-later"]` to deny.toml. I expect it to be accepted, since it's listed on https://spdx.org/licenses/. Instead, it gives a parse error:

```
; cargo deny check licenses
error: invalid licensee
   ┌─ /Users/jyn/src/redacted/deny.toml:16:14
   │
16 │     "LGPL-2.1-or-later",
   │              ^^^^^^^^^ expected a `<bare-gnu-license>` here

2023-04-26 14:23:53 [ERROR] failed to validate configuration file deny.toml
```

**To Reproduce**
1. `echo 'licenses.allow = ["LGPL-2.1-or-later"]' > deny.toml`
2. `cargo deny check licenses`

**Device:**
 - OS: MacOS 13.3.1, Darwin 22.4.0
 - Browser: N/A
 - Version: cargo-deny 0.13.9

**Comment by Jake-Shadle** [comment]
You need to leave off the `-or-later`. https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html#note-on-gnu-licenses

**Comment by EliteTK** [comment]
When you release source code with a GPL2 or GPL3 license, you can choose whether you want people with access to that source code to use it under the terms of only that license or if they can use it under the terms of a newer license.

This is correctly handled by cargo deny in that if I have a "GPL-2.0-only" dependency and deny.toml allows "GPL-3.0" then the license check will fail, but if I have a "GPL-2.0-or-later" dependency then cargo deny will correctly accept it in this case.

But! If I have a "GPL-3.0-only" dependency and my project is "GPL-3.0-or-later" then deny.toml doesn't allow me to prevent this scenario. If I have a "GPL-3.0-only" dependency in a "GPL-3.0-or-later" project then my project is mis-licensed, the project license has to be as restrictive as all other licenses combined, "-only" is more restrictive than "-or-later" and so my project must be licensed as "GPL-3.0-only".

Therefore, the difference between allowing "GPL-3.0" and "GPL-3.0-or-later" would be a useful distinction in these circumstances. As by allowing "GPL-3.0-or-later" instead of "GPL-3.0" I can correctly encode the requirement that I do not want "GPL-3.0-only" dependencies.

**Comment by Jake-Shadle** [comment]
Yah, I suppose the behavior could be improved for this kind of scenario. However, this would be extremely low priority for me since it's (IMO) a pretty niche problem.

If you are interested, the [spdx](https://github.com/EmbarkStudios/spdx/blob/main/src/licensee.rs) crate is the one responsible for parsing and evaluating license expressions,
