### ISSUE TITLE
Is a "Lockfile Only" mode possible, that doesn't require a Cargo.toml to be present?

### ISSUE THREAD

**Issue by jblebrun** [EmbarkStudios/cargo-deny#705]
**Is your feature request related to a problem? Please describe.**
I am working on a project that is using Bazel + `rules_rust`. We are working towards a bazel-only world (whether or not this is a good idea is a topic for another day 😆 ). 

We have some crates that do not use `Cargo.toml` files at all now, but we'd still like to be able to run `cargo-deny` checks on our entire dependency tree.

**Describe the solution you'd like**
A `cargo-deny` mode that only traverses specified `.lock` files, and doesn't require any `Cargo.toml` files to be present.

**Describe alternatives you've considered**
* The [cargo-audit](https://crates.io/crates/cargo-audit) project works without cargo, but it only supports a subset of the `cargo-deny` feature set.
* Also considering creating a synthetic project containing a minimal `Cargo.toml` for a project, and running cargo-deny on that fake project.

**Additional context**
If this is a reasonable ask, I'd be willing to implement it with some guidance on best approaches.

**Comment by Jake-Shadle** [comment]
If you generate lockfiles from Bazel that only includes the crates that are actually present in your final build artifacts that would maybe be doable, the issue would be if they would be the same as cargo generates, which would mean crates that you don't care about, like platform specific crates for platforms you never target, could still fail checks. Things like the license check would also tend to malfunction as the license/license-file metadata is in the cargo.toml file/cargo metadata, it's not present in the lockfiles.

I'd have no interest in implementing something like this myself since I don't use Bazel, but I'd accept a patch if it was reasonable.

**Comment by jblebrun** [comment]
Ah, thanks. I was definitely interested in the license functionality; good to know that that is a non-starter. 

Given that, it's probably not worth pursuing this idea further.
