### ISSUE TITLE
Bug: Cargo deny fails  with NFS

### ISSUE THREAD

**Issue by Arslan8** [EmbarkStudios/cargo-deny#712]
### Describe the bug

2024-10-30 17:46:18 [ERROR] failed to acquire advisory database lock: failed to obtain lock file '/home/faculty/abk6349/.cargo/advisory-dbs/db.lock': NFS do not support lockin

### To reproduce

I am using Ubuntu 24.04, and simply running cargo deny check results in this error. 
2024-10-30 17:46:18 [ERROR] failed to acquire advisory database lock: failed to obtain lock file '/home/faculty/abk6349/.cargo/advisory-dbs/db.lock': NFS do not support lockin

### cargo-deny version

v0.16.1

### What OS were you running cargo-deny on?

Linux

**Comment by Jake-Shadle** [comment]
Are you filing a bug because network file systems aren't supported like the error says, or are you asking for support for them? If the first...then this is working as intended, file locking is not supported on network file systems. If you are asking for this as a feature you'll most likely have to create a PR yourself if you want that feature since it would be incredibly low priority to implement since it's not a use case I have and it's easy to workaround by not using a NFS.

https://github.com/EmbarkStudios/tame-index/blob/feffa4962040a2629909a69b3929148a08646a39/src/utils/flock.rs#L217-L229

**Comment by Arslan8** [comment]
OK that makes sense! I didn't know NFS wasnt supported by cargo-deny..
